repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-ast
      - id: check-added-large-files
      - id: debug-statements
      - id: check-docstring-first
      - id: name-tests-test
        name: "Tests should start with test_"
        args: ["--django"]
      - id: requirements-txt-fixer
      - id: forbid-new-submodules
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.4.0
    hooks:
      - id: reorder-python-imports
        args: [--py3-plus]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
  - repo: https://github.com/python/black
    rev: 21.11b1
    hooks:
      - id: black
        args: [-l 79]
        language_version: python3
        files: ^magic_number/
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-typing-imports==1.7.0]
